### ISSUE TITLE
when will it work?

### ISSUE THREAD

**Issue by BLAST1718** [opZywl/EZ4H#3]

**Comment by Blackjack200** [comment]
__**It will work when it finished**__

**Comment by BLAST1718** [comment]
when will that be?

**Comment by hax0r31337** [comment]
idk

**Comment by hax0r31337** [comment]
but its now work on Nukkit,not work on PocketMine or BDS because the JWT data isn't correct

**Comment by hax0r31337** [comment]
you can download the daily build at http://ez4h.liulihaocai.gq/

**Comment by BLAST1718** [comment]
I dont use nukkit i use pmmp

**Comment by hax0r31337** [comment]
oh i know.u can star this repo and wait it supports JWT sign and join pmmp :D
