### ISSUE TITLE
连接超时

### ISSUE THREAD

**Issue by ghost** [opZywl/EZ4H#8]
![image](https://user-images.githubusercontent.com/63960170/105803060-93f75780-5fd7-11eb-912c-ee266aef43bc.png)

**Comment by Ootmnt150oO** [comment]
請把你伺服器端的 Xbox-auth給關閉

**Comment by hax0r31337** [comment]
xbox-auth目前有点问题，如果不希望没有正版验证的基岩版玩家加入服务器请安装[EZAuth](https://github.com/Project-EZ4H/EZAuth)插件~

**Comment by hax0r31337** [comment]
xbox-auth bug fixed
